name: 'Setup proto and moon toolchains bunifid'
author: 'Michal Lipinski'
description: 'Installs proto and moon globally when required, and caches the toolchain.'
inputs:
  auto-install:
    default: 'false'
    description: 'Auto-install tools on setup.'
  cache:
    description: 'Toggle caching of the toolchain directory.'
    default: 'true'
    required: false
  cache-base:
    description:
      'Base branch/ref to save a warmup cache on. Other branches/refs will restore from this base.'
  moon-version:
    default: ''
    description: 'Version of moon to install.'
    required: false
  proto-version:
    default: ''
    description: 'Version of proto to install.'
    required: false
  workspace-root:
    default: ''
    description: 'Path to the moon workspace root (if in a sub-directory).'
    required: false
outputs:
  cache-key:
    description: 'The cache key used for the toolchain folder (~/.proto).'
    value: ${{ steps.dist-index.outputs.cache-key }}
  cache-hit:
    description: 'A boolean to indicate an exact match was found for the cache key.'
    value: ${{ steps.dist-index.outputs.cache-hit }}
runs:
  using: 'composite'
  steps:
    - uses: oven-sh/setup-bun@v2
    - name: "run ci"
      id: dist-index
      run: bun run --bun ./dist/index.js
      shell: bash
    - name: "run post"
      run: bun run --bun ./dist/post.js
      shell: bash


branding:
  icon: 'battery-charging'
  color: 'purple'
