name: Publish
on:
  release:
    types: [published, edited]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build
      - uses: aboutte/build-and-tag-action@v2
        with:
          additional_files: 'dist/index,dist/post/index'
        env:
          GITHUB_TOKEN: ${{ github.token }}
